# docker-compose for demonstration purposes
version: "3.9"
services:
  postgres_db:
    # Accessible from containers via postgres://test:test@postgres_db:5432/test
    # Accessible from host machine via postgres://test:test@localhost:5433/test
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5433:5432"
  db-migration-tool:
    # Pull image from  public repository. Always
    image: kenho811/database-version-control:latest
    pull_policy: always
    depends_on:
      - postgres_db
    environment:
      - DVC__DATABASE_REVISION_SQL_FILES_FOLDER=sample_revision_sql_files
      - DVC__TARGET_SCHEMA=dvc
      - DVC__USER=test
      - DVC__PASSWORD=test
      - DVC__HOST=postgres_db
      - DVC__PORT=5432
      - DVC__DBNAME=test
      - DVC__DBFLAVOUR=postgres
      - DVC__LOGGING_LEVEL=DEBUG
    # Attach demo assets to the db-migration-tool and run scripts at start up
    working_dir: /usr/src/app/
    volumes:
      - .:/usr/src/app/
    entrypoint: /bin/bash
    command: ./demo_script.sh