name: Build and Push to Readthedocs

description: "Build and Push to Readthedocs"
inputs:
  rtds-webhook-url:
    required: true
    description: "Readthedocs Webhook URL"
  rtds-webhook-token:
    required: true
    description: "Readthedocs Webhook Token"
  commit-ref:
    required: true
    description: "Commit Ref for Readthedocs"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install -U pip
        python -m pip install -r docs/requirements.txt
        python -m pip install -e ".[dev]"
    - name: Build pytest report
      shell: bash
      run: |
        pytest --html=docs/dynamic/pytest/pytest_report.html -v
    - name: Build sphinx api doc
      shell: bash
      run: |
        sphinx-apidoc -o docs/dynamic/apidoc/source src
    - name: upload sphinx-apidoc .rst files
      uses: actions/upload-artifact@v2
      with:
        name: dynamic-asset-${{ github.sha }}
        path: docs/dynamic
    - name: Wait for complete upload of artifacts
      shell: bash
      run: |
        echo "Going to sleep for a while......Waiting until artifact is completed uploaded......"
        sleep 10
        echo "Sleeping is over!!!!"
    - name: Trigger RTDs build
      uses: dfm/rtds-action@v1
      with:
        webhook_url: ${{ inputs.rtds-webhook-url }}
        webhook_token: ${{ inputs.rtds-webhook-token }}
        commit_ref: ${{ inputs.commit-ref }}