name: Build and publish binaries

on:
  push:
    branches:
      - 'feature/gh_package'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Generate Binary
        run: pyinstaller --onefile --distpath ./dist --log-level=DEBUG  -n dvc ./src/dvc/app/cli/main.py
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::${{ github.ref_name }}_$(date +"%Y.%m.%d_%H-%M")"
      - name: Push to Github Releases
        uses: softprops/action-gh-release@v1
        with:
            tag_name: ${{ steps.tag.outputs.release_tag }}
            files: |
            ./dist/dvc