name: Test only

on:
  push:
    branches-ignore:
      - 'master'
      - 'release/**'
    tags-ignore:
      - 'release/**'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Run Pytest
        uses: ./.github/actions/run-pytest
        with:
          python-version: ${{ matrix.python-version }}