name: Test, build, push for master release (latest)

on:
  push:
    branches:
      - master

jobs:
  # Step 1: Run tests
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Run Pytest
        uses: ./.github/actions/run-pytest
        with:
          python-version: ${{ matrix.python-version }}

  # Step 2: Push to DockerHub
  build-n-push-docker-image:
    name: Build and push docker image and README.md to Dockerhub
    runs-on: ubuntu-latest
#    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Run docker image and README.md to DockerHub
        uses: ./.github/actions/build-n-push-to-dockerhub
        with:
          docker-image-tag: latest
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build-n-push-to-rtds:
    name: "Build artifacts for the docs"
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r docs/requirements.txt
          python -m pip install -e ".[dev]"

      - name: Build pytest report
        run: |
          pytest --html=docs/_static/pytest/report.html -v

      - uses: actions/upload-artifact@v2
        with:
          name: report-for-${{ github.sha }}
          path: docs/_static/pytest

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}