name: Test, build, push for tag releases


on:
  push:
    tags:
      - 'release/**'

jobs:
  # Step 1: Run tests
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Run Pytest
        uses: ./.github/actions/run-pytest
        with:
          python-version: ${{ matrix.python-version }}

  # Step 2a: Publish to PYPI
  build-n-push-to-PyPI:
    # Triggered after all tests run successfully
    name: Build and publish Python library to PyPI
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name:  Build and publish Python library to PyPI
        uses: ./.github/actions/build-n-push-to-PyPI
        with:
          pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}

  # Step 2: Build and Push to DockerHub
  build-n-push-to-dockerhub:
    name: Build and push docker image and README.md to Dockerhub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Build and push docker image and README.md to Dockerhub
        uses: ./.github/actions/build-n-push-to-dockerhub
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}

  # Push to rtds
  build-n-push-to-rtds:
    name: "Build and push artifacts to Readthedocs"
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Build and push artifacts to Readthedocs
        uses: ./.github/actions/build-n-push-to-rtds
        with:
          rtds-webhook-url: ${{ secrets.RTDS_WEBHOOK_URL }}
          rtds-webhook-token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit-ref: ${{ github.ref }}

  # Build binaries on different OSes and release
  build-mac-binary:
    needs: tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build, test and push Macos binaries as artifacts
        uses: ./.github/actions/build-n-push-binaries-to-ghrelease/build-n-push-mac-binary

  build-linux-binary:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build, test and push Linux binaries as artifacts
        uses: ./.github/actions/build-n-push-binaries-to-ghrelease/build-n-push-linux-binary

  build-windows-binary:
    needs: tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build, test and push Windows binaries as artifacts
        uses: ./.github/actions/build-n-push-binaries-to-ghrelease/build-n-push-windows-binary

  build-n-push-binaries-to-gh-release:
    needs: [build-mac-binary, build-linux-binary, build-windows-binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build, test and push binaries to Github Release
        uses: ./.github/actions/build-n-push-binaries-to-ghrelease
        with:
          gh-release-tag-name: ${{ github.ref }}
          gh-release-release-name: Release ${{ github.ref }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
